# Generated by Django 4.2.3 on 2023-07-31 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatAgent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.CharField(choices=[('user', 'User'), ('agent', 'Agent')], max_length=5),
        ),
    ]
