# Generated by Django 4.2.3 on 2023-07-31 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatAgent', '0002_alter_message_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=9),
        ),
    ]
